/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamChannelIdRouteImport } from './routes/api.stream.$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamChannelIdRoute = ApiStreamChannelIdRouteImport.update({
  id: '/api/stream/$channelId',
  path: '/api/stream/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/stream/$channelId': typeof ApiStreamChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/stream/$channelId': typeof ApiStreamChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/stream/$channelId': typeof ApiStreamChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/stream/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/stream/$channelId'
  id: '__root__' | '/' | '/api/stream/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStreamChannelIdRoute: typeof ApiStreamChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$channelId': {
      id: '/api/stream/$channelId'
      path: '/api/stream/$channelId'
      fullPath: '/api/stream/$channelId'
      preLoaderRoute: typeof ApiStreamChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStreamChannelIdRoute: ApiStreamChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
